public class DemoSampleClass {

   public DemoSampleClass{

    class myInnerClass {
        // myInnerClass code here
        // SYstem.out.print("Hello World");
          System.debug('Hello');


          //Added new Comment
          //kvkdfnvjfnjbntjbn
          //fnvnfdjvnfjnbjetf
          //vfkjnvkjfnvjnj
          //jkbvkjfnvjenfj
          //Added new Commen
          //dnckjndsvndiuviri
          //n jvbhfbvhfbiuvneifv
          //jvnsfkjnvjfvkjnfe
          //n vkjnfjkvnfjnvn

    }

}