public class DemoSampleClass {

   public DemoSampleClass{

    class myInnerClass {
        // myInnerClass code here
        // SYstem.out.print("Hello World");
          System.debug('Hello');


          //Added new Comment
          //kvkdfnvjfnjbntjbn
          //fnvnfdjvnfjnbjetf
          //vfkjnvkjfcdfvnjnonvjnjcnv kfnk
          //jkbvkjfnvjenfj
          //vfkjndhfoirhgihjsfjfnvjnj
          //jkbvkjfnvjenfja
          //Added new Commen
          //nfjgnfrnvgoien
          //vm dskjnvkjn 
          //dkvnskjdnvjn ornvl

    }

}