public with sharing class TrainingClass {
    public TrainingClass() {


        //vf fvjkfnjnfvj
        //v fkjvnfkjn
        //v cvkfnkj

         //njvnfreiriunv
         //fnekhbfiieurhfv
         //fkrmvfr,mvol
         //kfmrvdmvlkml


        //ndjoncvidnivunf
        //vlknjdfnvjnjvn
        //dnvjnvj djkvn

        //ndjndjenfji
        //fjnfkenwi
        //fkjnke

        //dhkfbhvufr
        //fdnfjnrjjr



    }
}